version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - mongo_network


      # Node api service
  api:
    build: 
     context: ./backend  
    ports:
      # local->container
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: cafe-db
    depends_on: 
      - mongo_db

volumes:
  mongo_data: {}

networks:
  mongo_network:
    driver: bridge
